### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ammgws** [ammgws/letssway#1]
- [ ] wdisplays - GUI display configurator for wlroots compositors [like arandr]
- [ ] wf-recorder - Screen recorder for wlroots-based compositors
- [ ] https://github.com/tadosappo/nasskan
- [ ] https://github.com/emersion/wlr-randr - An xrandr clone for wlroots compositors
- [ ] https://github.com/pedroscaff/swaywsr - Replace workstyler with this? Since former doesn't seem maintained. 
- [ ] https://github.com/neXromancers/uniconize - Might help with some games:
- [ ] https://github.com/cjbassi/swaylock-blur
- [ ] https://github.com/mortie/swaylock-effects
- [ ] https://github.com/activitywatch/aw-watcher-sway
- [ ] https://github.com/nirmoy/sway-time-tracker
- [ ] https://github.com/atx/wtype
- [ ] https://github.com/jtheoof/swappy

**Comment by WnndGws** [comment]
On it boss

**Comment by ammgws** [comment]
https://github.com/emersion/wlr-randr
An xrandr clone for wlroots compositors

**Comment by ammgws** [comment]
Replace workstyler with this https://github.com/pedroscaff/swaywsr?

Since former doesn't seem maintained. Haven't tried it out yet though.

**Comment by ammgws** [comment]
Might help with some games:

https://github.com/neXromancers/uniconize

**Comment by ammgws** [comment]
https://github.com/cjbassi/swaylock-blur
https://github.com/mortie/swaylock-effects

**Comment by ammgws** [comment]
https://github.com/atx/wtype

**Comment by WnndGws** [comment]
> https://github.com/cjbassi/swaylock-blur
> https://github.com/mortie/swaylock-effects

There are many swaylock alternatives. Should all of them be added, or is there a better way to handle them?

**Comment by WnndGws** [comment]
Can you edit your top-level comment to include all suggestions, and cross out those that are already added/rejected. This would make it easier to track progress rather than having to read and cross-reference the whole conversation

**Comment by ammgws** [comment]
No I cannot. Sorry

**Comment by ammgws** [comment]
> There are many swaylock alternatives. Should all of them be added, or is there a better way to handle them?

List them first? I only see two there.
